# Generated by Django 6.0.5 on 2026-07-02 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10000.0)], verbose_name='Costo'),
        ),
    ]
